version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spelling-bee
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  bee-service:
    image: spelling-bee-service
    platform: linux/amd64
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bee-server
    depends_on:
      - postgres
    ports:
      - 1337:1337

volumes:
  postgres-data:
